### ISSUE TITLE
does not answer to http requests on port 8000 when daemonized

### ISSUE THREAD

**Issue by ZaphodB** [ahupowerdns/metronome#10]
metronome does not seem to be responding to or even receiving packets on port [::]:8000 when daemonized. 

When started via

$ ./metronome --daemon=0 --stats-directory=./stats
Launched Carbon functionality on [::]:2003
Launched webserver on [::]:8000

it works as advertised.

**Comment by RvdE** [comment]
I have the exact same issue on FreeBSD 10.1

**Comment by ahupowerdns** [comment]
Zaphod, which OS are you on? When it happens, could you strace the whole thing? I can't reproduce here is the problem. Also, are you doubly sure you are connecting to [::]:8000 and not 127.0.0.1:8000?

**Comment by ahupowerdns** [comment]
RvdE: the strace question is for you as well of course ;-)

**Comment by ahupowerdns** [comment]
Ok, I can reproduce now. Pls wait.

**Comment by ahupowerdns** [comment]
Fixed in a33d01fa8f816cc760414861780291d326c7cf2a - this had to do with forking _after_ creating threads, which appears to work differently on some architectures than others.

**Comment by ahupowerdns** [comment]
actually fixed one commit later, sorry
