### ISSUE TITLE
Transfer-Encoding chunked and Content-Length set at the same time (yahttp)

### ISSUE THREAD

**Issue by wojas** [ahupowerdns/metronome#44]
Metronome uses an older version of yahttp that sets Transfer-Encoding chunked and Content-Length at the same time, which is not allowed and causes problems with newer HTTP clients that check this, like recent versions of NodeJS.

Solution: recent versions of yahttp fix this issue.

See:
- https://github.com/PowerDNS/pdns/issues/3723 
- https://github.com/cmouse/yahttp/issues/12

**Comment by pieterlexis** [comment]
fixed in #43
